# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=144)),
                ('date', models.DateField(default=None)),
                ('users', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rango.Friends')),
            ],
        ),
    ]
