# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('pub_date', models.DateField()),
                ('sender_id', models.IntegerField(null=True)),
                ('mtm', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('B', 'Big')], max_length=1)),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='messages',
            order_with_respect_to='pub_date',
        ),
    ]
