# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_friends_blocked'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='users',
        ),
        migrations.AddField(
            model_name='conversations',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rango.Friends'),
        ),
    ]
