# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20170812_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='date',
        ),
    ]
