# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_conversations_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
