# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversations_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversations',
            options={},
        ),
    ]
