# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listas_de_inclusao', models.CharField(max_length=2000)),
                ('denuncias', models.IntegerField()),
                ('spf', models.CharField(max_length=30)),
                ('erros_permanentes', models.CharField(max_length=200)),
                ('media_clicks_3_meses', models.CharField(max_length=10)),
                ('dominio_proprio', models.CharField(max_length=30)),
                ('nunca_interagiram', models.IntegerField()),
                ('contatos_base', models.IntegerField()),
                ('analise', models.DateTimeField()),
                ('html', models.CharField(max_length=10000)),
                ('campanha', models.CharField(max_length=200)),
                ('interacao_12_meses', models.IntegerField()),
                ('media_visualizacao_3_meses', models.CharField(max_length=10)),
                ('listas_de_exclusao', models.CharField(max_length=200)),
                ('campanhas_interrompidas_no_mes', models.IntegerField()),
                ('interacao_6_meses', models.IntegerField()),
                ('dkim', models.CharField(max_length=30)),
                ('segmentacao', models.CharField(max_length=200)),
                ('qualidade_de_base', models.CharField(max_length=3)),
            ],
        ),
    ]
