# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='cancelamentos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
