# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20170801_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default_change'),
            preserve_default=False,
        ),
    ]
