# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
