# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='list_friends',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
