# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_friends_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
